### ISSUE TITLE
Bug: Storyline alert appearing

### ISSUE THREAD

**Issue by cheng21tang** [cheng21tang/farQuest#84]
@Dylancouzon 
A storyline alert is appear during navigation of the story. Here I went left after the lake and forest and ran into the first enemy.
![storyline-alert](https://user-images.githubusercontent.com/80430929/117561512-46fe3500-b04c-11eb-9845-26f99b219e0c.PNG)

**Comment by Dylancouzon** [comment]
Fixed !
